services:
  mongodb:
    image: mongo:latest
    container_name: savings-challenge-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGO_REPLICA_HOST: ${MONGODB_HOST}
      MONGO_REPLICA_PORT: ${MONGODB_PORT}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: